name: p10-development
services:
  server:
    build:
      dockerfile: "../docker/development/SERVER.Dockerfile"
      context: "../../server"
    volumes:
      - "../../server:/app"
      - "../../server/prisma:/app/prisma"  
    ports:
      - "4000:4000"
      - "5555:5555"
    networks:
      - network
  
  db:
    image: postgres:16
    container_name: dev_bdd_postgres
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: F1database
    ports:
      - "5433:5432"
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  dev-db-data:
